---
- name: Common Tool Setup on all the Servers
  hosts: appsrvgrp
  become: true
  vars:
    tom_url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.37/bin/apache-tomcat-8.5.37.tar.gz

  tasks:
    - name: Install JDK on Centos 6/7
      ansible.builtin.yum:
        name: java-1.8.0-openjdk.x86_64
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Install JDK on Ubuntu 14/15/16/18
      ansible.builtin.apt:
        name: openjdk-8-jdk
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Download Tomcat Tar Ball/Binaries
      ansible.builtin.get_url:
        url: "{{ tom_url }}"
        dest: /tmp/tomcat-8.tar.gz

    - name: Add tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present

    - name: Add tomcat user
      ansible.builtin.user:
        name: tomcat
        group: tomcat
        shell: /bin/nologin
        home: /usr/local/tomcat8

    - name: Create /tmp/tomcat8 Directory
      ansible.builtin.file:
        path: /tmp/tomcat8
        state: directory

    - name: Extract tomcat
      ansible.builtin.unarchive:
        src: /tmp/tomcat-8.tar.gz
        dest: /tmp/tomcat8/
        remote_src: yes
        list_files: yes
      register: unarchive_info

    - ansible.builtin.debug:
        msg: "{{ unarchive_info.files[0].split('/')[0] }}"

    - name: Synchronize /tmp/tomcat8/tomcat_cont /usr/local/tomcat8.
      ansible.posix.synchronize:
        src: "/tmp/tomcat8/{{ unarchive_info.files[0].split('/')[0] }}/"
        dest: /usr/local/tomcat8/
      delegate_to: "{{ inventory_hostname }}"

    - name: Change ownership of /usr/local/tomcat8
      ansible.builtin.file:
        path: /usr/local/tomcat8
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Setup tomcat SVC file on Centos 7
      ansible.builtin.template:
        src: templates/epel7-svcfile.j2
        dest: /etc/systemd/system/tomcat.service
        mode: "a+x"
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

    - name: Setup tomcat SVC file on Centos 6
      ansible.builtin.template:
        src: templates/epel6-svcfile.j2
        dest: /etc/init.d/tomcat
        mode: "a+x"
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

    - name: Setup tomcat SVC file on ubuntu 14/15
      ansible.builtin.template:
        src: templates/ubuntu14_15-svcfile.j2
        dest: /etc/init.d/tomcat
        mode: "a+x"
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version < '16'

    - name: Setup tomcat SVC file on ubuntu 16 and 18
      ansible.builtin.template:
        src: templates/ubuntu16-svcfile.j2
        dest: /etc/systemd/system/tomcat.service
        mode: "a+x"
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version >= '16'

    - name: Reload tomcat svc config in ubuntu 14/15
      ansible.builtin.command: update-rc.d tomcat defaults
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version < '16'

    - name: Reload tomcat svc config in Centos 6
      ansible.builtin.command: chkconfig --add tomcat
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

    - name: just force systemd to reread configs (2.4 and above)
      ansible.builtin.systemd:
        daemon_reload: yes
      when: ansible_distribution_major_version > '6' or ansible_distribution_major_version > '15'

    - name: Start & Enable TOmcat 8
      ansible.builtin.service:
        name: tomcat
        state: started
        enabled: yes