---
- name: Setup Tomcat8 and Deploy Artifact
  hosts: appsrvgrp
  become: true
  vars:
    timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}_{{ ansible_date_time.minute }}"

  tasks:
    - name: Download latest VProfile.war from nexus
      ansible.builtin.get_url:
        url: "http://{{ USER }}:{{ PASS }}@{{ nexusip }}:8081/repository/{{ reponame }}/{{ groupid }}/{{ artifactid }}/{{ build }}-{{ time }}/{{ vprofile_version }}"
        dest: "/tmp/vproapp-{{ vprofile_version }}"
      register: wardeploy
      tags:
        - deploy

    - name: Get stats of /usr/local/tomcat8/webapps/ROOT File
      ansible.builtin.stat:
        path: /usr/local/tomcat8/webapps/ROOT
      register: artifact_stat
      tags:
        - deploy

    - name: Stop tomcat svc
      ansible.builtin.service:
        name: tomcat
        state: stopped
      tags:
        - deploy

    - name: Try Backup and Deploy
      block:
        - name: Archive ROOT dir with timestamp
          community.general.archive:
            path: /usr/local/tomcat8/webapps/ROOT
            dest: "/opt/ROOT_{{ timestamp }}.tgz"
          when: artifact_stat.stat.exists
          register: archive_info
          tags:
            - deploy

        - name: copy ROOT dir with old_ROOT name
          ansible.builtin.shell: cp -r ROOT old_ROOT
          args:
            chdir: /usr/local/tomcat8/webapps/

        - name: Delete current artifact
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          when: archive_info.changed
          loop:
            - /usr/local/tomcat8/webapps/ROOT
            - /usr/local/tomcat8/webapps/ROOT.war
          tags:
            - deploy

        - name: Try deploy artifact else restore from previos old_ROOT
          block:
            - name: Deploy vprofile artifact
              ansible.builtin.copy:
                src: "/tmp/vproapp-{{ vprofile_version }}"
                dest: /usr/local/tomcat8/webapps/ROOT.war
                remote_src: yes
              register: deploy_info
              tags:
              - deploy

          rescue:
            - ansible.builtin.shell: cp -r old_ROOT ROOT
              args:
                chdir: /usr/local/tomcat8/webapps/

      rescue:
        - name: Start tomcat svc
          ansible.builtin.service:
            name: tomcat
            state: started

    - name: Start tomcat svc
      ansible.builtin.service:
        name: tomcat
        state: started
      when: deploy_info.changed
      tags:
        - deploy

    - name: Wait until ROOT.war is extracted to ROOT directory
      ansible.builtin.wait_for:
        path: /usr/local/tomcat8/webapps/ROOT
      tags:
        - deploy

    - name: Deploy web configuration file
      ansible.builtin.template:
        src: templates/application.j2
        dest: /usr/local/tomcat8/webapps/ROOT/WEB-INF/classes/application.properties
        force: yes
      notify:
      - Restart Tomcat
      tags:
      - deploy

  handlers:
    - name: Restart Tomcat
      ansible.builtin.service:
        name: tomcat
        state: restarted